# Generated by Django 5.0.1 on 2024-02-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('kode_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=30)),
                ('jenis', models.CharField(max_length=30)),
                ('outlet', models.CharField(max_length=30)),
                ('harga_modal', models.IntegerField()),
                ('harga_jual', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('sum_of_modal', models.IntegerField()),
                ('sum_of_jual', models.IntegerField()),
                ('income_unit', models.IntegerField()),
                ('sum_of_income', models.IntegerField()),
                ('no_user', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='kumpulan_cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cashier', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='kumpulan_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_table', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='master',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('no_table', models.IntegerField()),
                ('tanggal', models.DateTimeField()),
                ('total_amount', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pay', models.IntegerField()),
                ('kembalian', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='numbertable',
            fields=[
                ('id_no', models.IntegerField(primary_key=True, serialize=False)),
                ('number_table', models.IntegerField()),
                ('cashier_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='numbertable3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_table', models.IntegerField()),
                ('cashier_name', models.CharField(max_length=30)),
                ('no_user', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orderss6',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('no_table', models.IntegerField()),
                ('kode_barang', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('nama_barang', models.CharField(max_length=30)),
                ('harga_jual', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_harga', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('no_user', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pendaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_usaha', models.CharField(max_length=50)),
                ('nama_toko', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('Jumlah_anggota', models.CharField(max_length=20)),
                ('skala', models.CharField(max_length=20)),
                ('whatssapp', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='penjualan',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('no_table', models.IntegerField()),
                ('kode_barang', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('nama_barang', models.CharField(max_length=30)),
                ('harga_jual', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='report_table',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('no_table', models.IntegerField()),
                ('tanggal', models.DateTimeField()),
                ('total_amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tablee66',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_table', models.IntegerField(null=True)),
                ('nomor_meja', models.IntegerField(null=True)),
                ('no_user', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('no_table', models.IntegerField()),
                ('kode_barang', models.IntegerField()),
                ('tanggal', models.DateTimeField()),
                ('nama_barang', models.CharField(max_length=30)),
                ('harga_jual', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_harga', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('kode_barang', models.IntegerField()),
                ('tanggal', models.DateTimeField()),
                ('nama_barang', models.CharField(max_length=30)),
                ('harga_jual', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transaction_done',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('no_table', models.IntegerField()),
                ('tanggal', models.DateTimeField()),
                ('total_amount', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('kembalian', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transaction_finish',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('no_table', models.IntegerField()),
                ('tanggal', models.DateTimeField()),
                ('total_amount', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('kembalian', models.IntegerField()),
            ],
        ),
    ]
