# Generated by Django 5.0.1 on 2024-02-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tablee6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_table', models.IntegerField(null=True)),
                ('nomor_meja', models.IntegerField(null=True)),
                ('no_user', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
