# Generated by Django 5.0.1 on 2024-02-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tablee6'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='no_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
