# Generated by Django 5.0.1 on 2024-02-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_temp_no_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumpulan_cashier',
            name='no_user',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='kumpulan_table',
            name='no_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
