# Generated by Django 5.0.1 on 2024-02-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_kumpulan_cashier_no_user_kumpulan_table_no_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_table',
            name='no_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
