# Generated by Django 5.0.1 on 2024-02-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_report_table_no_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_table',
            name='transaction_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
