# Generated by Django 5.0.1 on 2024-02-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_report_table_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='out',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='tersisa',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
