# Generated by Django 5.0.1 on 2024-02-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_database_out_database_tersisa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='out',
            new_name='out_barang',
        ),
    ]
