# Generated by Django 5.0.1 on 2024-02-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_out_database_out_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='kode_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
