# Generated by Django 5.0.1 on 2024-02-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_database_kode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderss6',
            name='kode_barang',
            field=models.BigIntegerField(),
        ),
    ]
