# Generated by Django 5.0.1 on 2024-02-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_orderss6_kode_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan',
            name='kode_barang',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='temp',
            name='kode_barang',
            field=models.BigIntegerField(),
        ),
    ]
