# Generated by Django 5.0.1 on 2024-02-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_penjualan_kode_barang_alter_temp_kode_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='no_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
