# Generated by Django 5.0.1 on 2024-02-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_history_no_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_done',
            name='no_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
